services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
      - ./logs:/logs
    networks:
      - spark_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./data/checkpoints:/data/checkpoints
      - ./etl/transform_load:/opt/spark-apps
      - ./.env:/opt/spark-apps/.env
    command: >
      spark-submit
      --master local[*]
      /opt/spark-apps/spark_streaming_to_postgres.py
    networks:
      - spark_network

volumes:
  postgres_data:

networks:
  spark_network:
    driver: bridge
